alert("aiman khan");
alert("thanks for your input");
var val=10;
document.write('the value of a is:',val);
document.write("<br>");
document.write('...................');
document.write("<br>");
document.write('the value of ++a is',++val);
document.write("<br>");
document.write("<br>");
document.write('now the value of a is 11');
document.write("<br>");
document.write("<br>");
document.write("<br>");
document.write('the value of a++ is',val++);
document.write("<br>");
document.write("<br>");
document.write('now the value of a is 12');
document.write("<br>");
document.write("<br>");
document.write('the value of --a is',--val);
document.write("<br>");
document.write("<br>");
document.write('now the value of a is 11')
document.write("<br>");
document.write("<br>");
document.write('the value of a-- is',val--);
document.write("<br>");
document.write("<br>");
document.write('now the value of a is 10');
document.write("<br>");
document.write("<br>");

document.write("<br>");
document.write("<hr>");
var one=1;
document.write('a is',one);
document.write("<br>");
var two=2;
document.write('b is' ,two);
document.write("<br>");
document.write('total value is:3')
document.write("<br>");
document.write("<hr>");
document.write("ALERT");
document.write("<hr>");
alert("“▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬”");